language: ruby
sudo: false
bundler_args: --jobs 4 --without integration
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
script:
  - bundle exec rake
notifications:
  email:
    recipients:
      - krone.adam@gmail.com
